version: 1
policies:
  - id: AWS_Security_Group_Policy:unrestricted_ingress
    when:
      checkers:
        - unrestricted_ingress_terraform_aws_security_group
    result:
      exit-code: 1
      message: AWS_Security_Group_Policy:unrestricted_ingress / Defect from aws_security_group
      
  - id: Warning-Policy:warning-sev
    when:
      severity: warning
    result:
      exit-code: 1
      message: arning-Policy:warning-sev message / Defect from warning severity checker caused failure
{"mode":"full","isActive":false}
